### ISSUE TITLE
Tan solo imprime el ID del iframe.

### ISSUE THREAD

**Issue by Diegopintos** [sergiois/cfivoox#2]
Hola seguramente funciona perfectamente pero a mi no.
he probado otros campos que también utilizan iframe y estes genial pero el tuyo no termina de visualizarse tan solo imprime el id del ivox.

**Comment by sergiois** [comment]
Hola! Acabo de probar en la demo que tengo y funciona correctamente.
Las plantillas utilizadas están basadas en Bootstrap 2, 3 y 4 y UiKit
¿Podrías decirme qué plantilla utilizas o alguna pista para intentar ver por qué no te funciona?

**Comment by Diegopintos** [comment]
Pues estoy utilizando una plantilla basada en uikit3

**Comment by sergiois** [comment]
La plantilla que tengo es UiKit versión 2 (yoo_master2). De la nueva versión, la 3, no tengo ninguna para poder realizar pruebas.

**Comment by Diegopintos** [comment]
tal vez sea porque el iframe de ivoox haya cambiando?

**Comment by sergiois** [comment]
No creo. Porque en las plantillas que te comento está funcionando correctamente
Tiene que ser algo de la plantilla. Le preguntaré a @carcam que lo utiliza en uno de sus proyectos a ver si él me puede decir algo.

**Comment by Diegopintos** [comment]
Gracias @sergiois  siento ser yo el da el aviso. Pero es que exactamente este campo es el hace tiempo que estaba buscando. I ni siquiera sabia que se podían crear campos super presonalizados.
Larga vida Joomla

**Comment by sergiois** [comment]
Hola de nuevo. He preguntado a @carcam y me comenta que su template es UiKit 3. Revisando su proyecto veo que se carga perfectamente el iframe de iVoox. Puedes verlo en https://mastermindjoomla.com/38-joomla-3-9-privacidad-en-el-core
Sin ver tu proyecto no puedo analizar posibles errores.

**Comment by Diegopintos** [comment]
Hola, aun en fase de construcción en cuanto lo suba al servidor enlazo.
@sergiois  Sabes donde puedo encontrar documentación para maquetar los campos en el articulo de mi plantilla. (ahora mismo los visualiza de forma automática)
Me gustaría hacerlo de forma nativa picando código en el frontend article y lo único que he encontrado es la creación de estos  y muchísima información relacionado con extensiones de terceros para hacerlo.

**Comment by sergiois** [comment]
Aquí tienes información sobre campos personalizados en override:
- https://docs.joomla.org/J3.x:Adding_custom_fields/Overrides

**Comment by carcam** [comment]
Por referencias (si sabéis cómo me pongo para qué me llamais...) te digo que para maquetar fácilmente los campos personalizados puedes usar [Easy Layouts](https://www.easylayouts.net). Es lo que yo suelo usar en mis proyectos (entre otras cosas porque formo parte del equipo de desarrollo #SpamIsSexy :P) Si quieres una copia para evaluarlo, no dudes en contactarme por privado.

Con respecto a tu problema, lo cierto es que "No funciona" no aporta mucho. El código del plugin solo muestra un iframe, y siempre y cuando el campo del artículo tenga algún valor (vamos que no esté en blanco), te va a insertar el iframe por lo que yo miraría primero si hay algún iframe en el código de la página generada o no.

Por otro lado revisa bien los permisos del campo y la configuración que tengas para mostrarlo...

**Comment by carcam** [comment]
¿sólo imprime el ID? ¿Te refieres al ID del podcast o al código del iframe? Una captura de pantalla o cortar y pegar el código en cuestión nos podría ayudar....

**Comment by carcam** [comment]
¿sólo imprime el ID? ¿Te refieres al ID del podcast o al código del iframe? Una captura de pantalla o cortar y pegar el código en cuestión nos podría ayudar....
